// Builds /home/raymond/ws1-toolkit/src/library/catalog.ts by merging every
// OpenAPI spec under docs/specs/. The specs were captured from a real
// tenant's /api/help/Docs/<name> endpoint — re-fetch them with curl and
// rerun this script to refresh.
//
// Run: node scripts/build-catalog.mjs

import { readFileSync, writeFileSync, readdirSync } from "fs";

const SPECS_DIR = "/home/raymond/ws1-toolkit/docs/specs";
const OUT = "/home/raymond/ws1-toolkit/src/library/catalog.ts";

const METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE"];

function specToEntries(spec) {
  if (!spec || typeof spec !== "object") return [];
  const paths = spec.paths ?? {};

  // Resolve basePath. Swagger 2.0: top-level `basePath`. OpenAPI 3.0:
  // first server's url (we want only the pathname).
  let basePath = "";
  if (typeof spec.basePath === "string") {
    basePath = spec.basePath;
  } else if (Array.isArray(spec.servers) && spec.servers.length > 0) {
    const url = spec.servers[0]?.url;
    if (typeof url === "string") {
      try {
        basePath = new URL(url).pathname || "";
      } catch {
        basePath = url;
      }
    }
  }
  basePath = basePath.replace(/\/$/, "");

  const out = [];
  for (const [rawPath, ops] of Object.entries(paths)) {
    if (!ops || typeof ops !== "object") continue;
    const fullPath = `${basePath}${rawPath.startsWith("/") ? "" : "/"}${rawPath}`;
    for (const m of METHODS) {
      const op = ops[m.toLowerCase()];
      if (!op) continue;

      const tags = Array.isArray(op.tags) ? op.tags : [];
      const category = tags[0] ?? "Uncategorised";
      const summary = typeof op.summary === "string" ? op.summary : "";
      const rawDesc =
        typeof op.description === "string" && op.description.length > 0
          ? op.description
          : summary || (typeof op.operationId === "string" ? op.operationId : "");

      const isNew = /^\s*new\b\s*-?\s*/i.test(summary);
      const description = rawDesc.replace(/^\s*new\b\s*-?\s*/i, "").trim();

      out.push({
        category,
        method: m,
        path: fullPath,
        description,
        ...(isNew ? { isNew: true } : {}),
      });
    }
  }
  return out;
}

const merged = new Map();
const specFiles = readdirSync(SPECS_DIR)
  .filter((f) => f.endsWith(".json"))
  .sort();

let totalSourceEntries = 0;
for (const file of specFiles) {
  const spec = JSON.parse(readFileSync(`${SPECS_DIR}/${file}`, "utf-8"));
  const entries = specToEntries(spec);
  totalSourceEntries += entries.length;
  for (const e of entries) {
    const key = `${e.method} ${e.path}`;
    const existing = merged.get(key);
    // Prefer the entry with the longer description (richer doc).
    if (!existing || e.description.length > existing.description.length) {
      merged.set(key, e);
    }
  }
  console.log(`  ${file.padEnd(20)} ${entries.length} entries`);
}

const final = [...merged.values()].sort(
  (a, b) =>
    a.category.localeCompare(b.category) ||
    a.path.localeCompare(b.path) ||
    a.method.localeCompare(b.method)
);

const byCategory = {};
for (const e of final) byCategory[e.category] = (byCategory[e.category] || 0) + 1;
console.log(
  `\nMerged ${totalSourceEntries} source entries → ${final.length} unique endpoints across ${Object.keys(byCategory).length} categories.`
);

const head = `// Auto-generated by scripts/build-catalog.mjs from docs/specs/*.json.
// Sources: ${specFiles.join(", ")}
// Re-fetch the specs (curl /api/help/Docs/<name>) and rerun the script
// to refresh.

export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export interface CatalogEndpoint {
  category: string;
  method: HttpMethod;
  /** Path is the relative path under the tenant base URL (e.g. "/api/mdm/tags/addtag"). */
  path: string;
  description: string;
  isNew?: boolean;
}

export const CATALOG: CatalogEndpoint[] = `;

const tail = ` as const;

/** All distinct categories in the catalog, in alphabetical order. */
export const CATALOG_CATEGORIES: string[] = (() => {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const e of CATALOG) {
    if (!seen.has(e.category)) {
      seen.add(e.category);
      out.push(e.category);
    }
  }
  return out;
})();
`;

writeFileSync(OUT, head + JSON.stringify(final, null, 2) + tail);
console.log(`\nWrote ${OUT}`);
