// Parses /home/raymond/ws1-toolkit/docs/ws1-mdm-v1-api-reference.md
// and emits /home/raymond/ws1-toolkit/src/library/catalog.ts.
//
// Run: node scripts/build-catalog.mjs

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { dirname } from "path";

const SRC = "/home/raymond/ws1-toolkit/docs/ws1-mdm-v1-api-source.md";
const OUT = "/home/raymond/ws1-toolkit/src/library/catalog.ts";

const md = readFileSync(SRC, "utf-8");

// Match section headers like "## SmartGroups"
// Match endpoint lines like "- **POST** `/path` — description"
// Or "- `/path` — description" (when method is unclear in source — rare)

const lines = md.split("\n");
let currentCategory = null;
const endpoints = [];

const HEADER_RE = /^##\s+(.+)$/;
const ENDPOINT_RE = /^-\s+\*\*(GET|POST|PUT|PATCH|DELETE)\*\*\s+`([^`]+)`\s+—\s+(.+)$/;
// Some entries are missing the method — skip those silently.

for (const raw of lines) {
  const line = raw.trimEnd();
  const headerMatch = line.match(HEADER_RE);
  if (headerMatch) {
    currentCategory = headerMatch[1].trim();
    continue;
  }
  const endpointMatch = line.match(ENDPOINT_RE);
  if (endpointMatch && currentCategory) {
    let [, method, path, desc] = endpointMatch;
    desc = desc.trim();
    let isNew = false;
    if (desc.startsWith("New - ")) {
      isNew = true;
      desc = desc.slice("New - ".length);
    }
    endpoints.push({ category: currentCategory, method, path, description: desc, isNew });
  }
}

// Skip categories that are out-of-scope reference text (e.g. "Schemas", "Quick map")
const STOP_CATEGORIES = new Set([
  "Schemas",
  "Quick map: what we currently use vs the spec",
  "Action items based on this spec",
]);
const filtered = endpoints.filter((e) => !STOP_CATEGORIES.has(e.category));

// Group counts for sanity
const byCategory = {};
for (const e of filtered) {
  byCategory[e.category] = (byCategory[e.category] || 0) + 1;
}

console.log(`Parsed ${filtered.length} endpoints across ${Object.keys(byCategory).length} categories.`);
for (const [cat, count] of Object.entries(byCategory)) {
  console.log(`  ${cat.padEnd(50)} ${count}`);
}

// Emit TS file
const head = `// Auto-generated by scripts/build-catalog.mjs from docs/ws1-mdm-v1-api-reference.md.
// Do NOT edit by hand — re-run the script after updating the source markdown.

export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export interface CatalogEndpoint {
  category: string;
  method: HttpMethod;
  /** Path is the relative path under the tenant base URL (e.g. "/api/mdm/tags/addtag"). */
  path: string;
  description: string;
  isNew?: boolean;
}

export const CATALOG: CatalogEndpoint[] = `;

// Each catalog entry should include the /api/mdm prefix for paths in this section
// (the source markdown lists relative paths like "/devices/{id}" — we prepend the
// /api/mdm root for use with our existing WS1 client).
const withApiPrefix = filtered.map((e) => ({
  ...e,
  path: e.path.startsWith("/api/") ? e.path : "/api/mdm" + e.path,
}));

const tsBody = JSON.stringify(withApiPrefix, null, 2);

const tail = ` as const;

/** All distinct categories in the catalog, in original ordering. */
export const CATALOG_CATEGORIES: string[] = (() => {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const e of CATALOG) {
    if (!seen.has(e.category)) {
      seen.add(e.category);
      out.push(e.category);
    }
  }
  return out;
})();
`;

const outDir = dirname(OUT);
if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
writeFileSync(OUT, head + tsBody + tail);
console.log(`\nWrote ${OUT}`);
